PetriNET/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    BusStopView,
    BusStopViewSet,
    CalculationViewSet,
    CityView,
    CityViewSet,
    DistrictViewSet,
    EIViewSet,
    MainMap,
    RouteView,
    RouteViewSet,
    SimulationViewSet,
    TCViewSet,
    download_report_file,
)

app_name = 'PetriNET'

# Создаем роутер для API
api_router = DefaultRouter()
api_router.register(r'cities', CityViewSet, basename='city')
api_router.register(r'transport-types', TCViewSet, basename='tc')
api_router.register(r'busstops', BusStopViewSet, basename='busstop')
api_router.register(r'routes', RouteViewSet, basename='route')
api_router.register(r'districts', DistrictViewSet, basename='district')
api_router.register(r'calculations', CalculationViewSet, basename='calculation')
api_router.register(r'simulations', SimulationViewSet, basename='simulation')
# api_router.register(r'measurement-units', EIViewSet, basename='ei')


urlpatterns = [
    path('', MainMap.as_view(), name='main_map'),
    path('api/', include(api_router.urls)),
    path('ajax/city/get', CityView.as_view(), name='get_city_data'),
    path('ajax/BS/add', BusStopView.as_view(), name='create_bs'),
    path('ajax/BS/get', BusStopView.as_view(), name='get_bs'),
    path('ajax/route/add', RouteView.as_view(), name='create_route'),
    path('ajax/download_report_file', download_report_file, name='download_report_file'),
]

TransportMap/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
    # API документация
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    
    # Основные страницы приложения
    path('', include('PetriNET.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountLogin, AccountLogout, AccountRegister #, lk, paid
)

app_name = 'accounts'

urlpatterns = [
    path('login/', AccountLogin.as_view(), name='login'),
    path('register/', AccountRegister.as_view(), name='register'),
    path('logout/', AccountLogout.as_view(), name='logout'),
]

accounts/models.py
from django.db import models

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.views.generic import CreateView
from django.urls import reverse_lazy

from accounts.forms import CustomAuthenticationForm, CustomUserCreationForm

class AccountLogin(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'accounts/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context
    
    def get_success_url(self):
        url = self.get_redirect_url()
        if url:
            return url
        else:
            return reverse_lazy("PetriNET:main_map")


class AccountLogout(LogoutView):
    next_page = reverse_lazy('PetriNET:main_map')


class AccountRegister(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('PetriNET:main_map')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def post(self, *args, **kwargs):
        response = super().post(*args, **kwargs)
        if self.object:
            self.object.is_superuser = True
            login(self.request, self.object)

        return response

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    Удаление пользоватлея "{{ object.username }}"
    <form method="POST">
        {% csrf_token %}
        <span>Пользователь "{{ object.username }}" будет удален без возможности восстановления. Удалить пользователя?</span>
        <br>
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock %}

{% block body %}
    <div class="container d-flex align-items-center justify-content-center text-center" style="min-height: 100vh;">
        <div class="card">
            <div class="card-body">
                <img class="mb-4" src="{% static 'bus-solid.svg' %}" alt="" width="72" height="72">
                {% block lable %}
                    <h2 class="card-title mb-4">Вход <a href="{% url 'accounts:register' %}">регистрация</a></h2>
                <form method="post" action="{% url 'accounts:login' %}">
                {% endblock %}
                    {% csrf_token %}
                    <div class="container">
                        {% for field in form %}
                        <div class="row mb-3">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">{{ field.label }}</span>
                                </div>
                                {{ field }}
                            </div>
                        </div>
                        {% if field.errors %}
                            <div class="row mb-3">
                                {% for error in field.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% for err in form.non_field_errors %}
                    <div class="alert alert-danger w-100" role="alert">
                        {{ err }}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary mt-3 w-100">Войти</button>
                </form>
                <p class="mt-4 text-muted">© 2023-2025</p>
            </div>
        </div>
    </div>
{% endblock %}


{% block endjs %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'accounts/login.html' %}
{% load static %}

{% block lable %}
<h2 class="card-title mb-4"><a href="{% url 'accounts:login' %}">Вход</a> регистрация</h2>
<form method="post" action="{% url 'accounts:register' %}">
{% endblock %}